import { LandingClient } from "./landing-client";
import { SITE_NAME, SITE_URL } from "@/lib/site-config";
import type { Metadata } from "next";

const title = `${SITE_NAME} – Turn podcasts into content in minutes`;
const description =
  "Upload podcast or interview audio. Get SEO-ready blog posts, tweets, LinkedIn posts, show notes, and more—generated by AI so you can publish faster.";

export const metadata: Metadata = {
  title,
  description,
  openGraph: {
    title,
    description,
    url: SITE_URL,
    siteName: SITE_NAME,
    type: "website",
  },
  twitter: { card: "summary_large_image", title, description },
  alternates: { canonical: SITE_URL },
};

export default function HomePage() {
  return <LandingClient />;
}
